spring:
 app:
  name: App Onboarding
 profiles:
  active: dev

server:
 port: 8081

logging:
 config: classpath:log4j2-${spring.profiles.active}.yml

csv:
 file:
  path: C:/Users/VS752YJ/Downloads/appOnboarding/appOnboarding/industry.csv
env:
 file:
  path: ${CSV_FILE_PATH}